name: Tweet Bot

on:
  schedule:
    - cron: '*/10 * * * *'  # Run every 10 minutes
  workflow_dispatch:  # Allows manual triggering

jobs:
  tweet:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        echo "Installed packages:"
        pip list
    
    - name: Download tweet history
      run: |
        # Create empty history file if it doesn't exist
        if [ ! -f tweet_history.json ]; then
          echo '{"posted_tweets": [], "last_cleanup": "'$(date -Iseconds)'"}' > tweet_history.json
        fi
    
    - name: Run tweet bot
      env:
        API_KEY: ${{ secrets.API_KEY }}
        API_SECRET: ${{ secrets.API_SECRET }}
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
        GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
      run: |
        echo "Running tweet bot..."
        python test.py || echo "Tweet bot failed, check logs for details"
    
    - name: Commit and push tweet history
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add tweet_history.json
        git diff --staged --quiet || (git commit -m "Update tweet history [skip ci]" && git push) || echo "No changes to commit"