name: Tweet Bot

on:
  schedule:
    # Run every 2 hours
    - cron: '0 */2 * * *'
  workflow_dispatch: # Allows manual triggering

jobs:
  tweet:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Download tweet history
      run: |
        # Create empty history file if it doesn't exist
        if [ ! -f tweet_history.json ]; then
          echo '{"posted_tweets": [], "last_cleanup": "'$(date -Iseconds)'"}' > tweet_history.json
        fi
    
    - name: Run tweet bot
      env:
        API_KEY: ${{ secrets.API_KEY }}
        API_SECRET: ${{ secrets.API_SECRET }}
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
      run: python tweet_generator.py
    
    - name: Commit and push tweet history
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add tweet_history.json
        git diff --staged --quiet || git commit -m "Update tweet history [skip ci]"
        git push